# image will be published to ghcr.io/<user>/<name>
name: ublue-nicc
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: latest
modules:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.gitlab.librewolf-community
        - com.logseq.Logseq
        - org.signal.Signal
        - org.telegram.desktop
        - net.mullvad.MullvadBrowser
      remove:
        - org.mozilla.firefox

  - type: signing
